### ISSUE TITLE
Accordion shows blank when under ACF Tab

### ISSUE THREAD

**Issue by PthPndr** [bvdr/acf-accordion#3]
I have a row of normal ACF tabs. If I add an accordion tab under the first ACF tab everything is fine. If I add an accordion tab under any of the other ACF tabs, the accordion tab is blank.

I attached a screenshot of what I am seeing. Any help would be greatly appreciated.
I should mention I am running the latest (5.3.2.1) version of ACF Pro.

![accordion tab](https://cloud.githubusercontent.com/assets/11739012/11074498/e725e7b6-87bd-11e5-8937-3125b1c118f1.png)

**Comment by JakedUp** [comment]
I can confirm that this is an issue as well. A fix would be greatly appreciated!!!

**Comment by druellan** [comment]
I'm having this problem again on `4.4.11` Seems that there is a new class type `.acf-tab_group-hide` added to the field group, that has an extra `display: none`.

I have a quick fix up and running:
https://github.com/bvdr/acf-accordion/compare/master...druellan:master
